### ISSUE TITLE
How to use UI but at a different URL than /login-api

### ISSUE THREAD

**Issue by shellking4** [femike/swagger-protect#10]
Thanks for the work on this package.

I don't want to set up a login form. I want to use the ui that comes with the package but still be able to customize the URL on which I can access it. eg: /api/v1/docs/login

**Comment by femike** [comment]
As you can see url is hardcoded in the UI component, you can fork it, rebuild and replace as your own package. 
https://github.com/femike/swagger-protect-ui/blob/85ac094bfdf1c87209d02907c1588b2ada1b4f0e/src/components/LoginForm.vue#L165

**Comment by xtrinch** [comment]
@femike Would this not be possible to be added into this package? Seems like such a small change to introduce own fork for this
