### ISSUE TITLE
Getting 404 with setGlobalPrefix

### ISSUE THREAD

**Issue by behzadmoradi** [femike/swagger-protect#5]
if I use `app.setGlobalPrefix('api/v1');`, I will get the following error:
`http://localhost:3100/login-api 404 (Not Found)`

**Comment by femike** [comment]
Which adapter do you use `express` or `fastify`?

**Comment by femike** [comment]
You can use exclude

```ts
app.setGlobalPrefix('api/v1', {
    exclude: ['/login-api'],
})
 ```
