### ISSUE TITLE
Update request : Fix critical vulnerability + Update to NestJS 9 and Fastify 4

### ISSUE THREAD

**Issue by Drarox** [femike/swagger-protect#6]
Nice package, however, could you please update the package to fix the critical vulnerability and update to NestJS 9 and Fastify 4 so it can work with the current version of the framework.

`14 vulnerabilities (3 moderate, 10 high, 1 critical)`

I would do it myself and make a Pull request, but the 'src' folder with the source files is missing on the github repo.

Thank you

**Comment by femike** [comment]
#7 Thanks released v9.0.3 🍟
